Repository PrestaShopCorp/ps_checkout, pull requests merged in 2019-12, with the labels that each got.

#226 Enable Release Drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: Feature

#228 fix 1.7.3 compat
  .travis.yml
  classes/Presenter/Cart/CartPresenter.php
Labels: bug

#231 Run PHPStan with several versions of PrestaShop
  .travis.yml
  tests/phpstan/phpstan.neon
Labels: enhancement

#227 EMOD-229 activate all countries by default
  ps_checkout.php
Labels: enhancement

#224 EMOD-304 update order states colors
  classes/OrderStates.php
  upgrade/upgrade-1.2.9.php
Labels: enhancement

#233 Add php linter action
  .github/workflows/php.yml
  .prettyci.composer.json
Labels: enhancement

#237 update cgu links
  classes/Presenter/Store/Modules/ContextModule.php
  docs/cgu_fr.pdf
Labels: Need Review

#221 Adds logs on api calls
  classes/Api/GenericClient.php
  classes/Factory/CheckoutLogger.php
  classes/Factory/index.php
  ps_checkout.php
  tests/PaymentCreateOrderTest.php
Labels: enhancement

#238 add trad to payment by card text
  classes/ValidateOrder.php
Labels: need review
