Repository PrestaShopCorp/ps_checkout, pull requests merged in 2020-02, with the labels that each got.

#287 Change of OrderState should send mail if needed
  classes/Refund.php
  classes/ValidateOrder.php
  classes/webHookDispatcher/OrderDispatcher.php
  ps_checkout.php
Labels: bug

#290 Fix fatal error on DispatchWebHook
  controllers/front/DispatchWebHook.php
Labels: bug

#291 Add locale parameter to express checkout button
  classes/Adapter/LanguageAdapter.php
  classes/Builder/Payload/OnboardingPayloadBuilder.php
  classes/ExpressCheckout.php
  views/templates/front/expressCheckout.tpl
Labels: enhancement

#292 Fix fatal error on ps version older than 1.6.1.15
  classes/Adapter/LinkAdapter.php
Labels: bug

#288 handle icon copy when file does not exist
  classes/OrderStates.php
  upgrade/upgrade-1.2.14.php
Labels: enhancement

#299 Add github action in place of travis
  .github/workflows/build-release.yml
  .github/workflows/js.yml
  .github/workflows/release-drafter.yml
  .travis.yml
Labels: enhancement

#281 Multishop compatibility
  _dev/src/App.vue
  classes/Api/Firebase/Token.php
  classes/Api/GenericClient.php
  classes/Api/Payment/Client/PaymentClient.php
  classes/Api/Psx/Client/PsxClient.php
  classes/Builder/Payload/OnboardingPayloadBuilder.php
  classes/Builder/Payload/OrderPayloadBuilder.php
  classes/Environment/Env.php
  classes/ExpressCheckout.php
  classes/OrderStates.php
  classes/PersistentConfiguration.php
  classes/Presenter/Store/Modules/ConfigurationModule.php
  classes/Presenter/Store/Modules/ContextModule.php
  classes/Presenter/Store/Modules/FirebaseModule.php
  classes/Presenter/Store/Modules/PsxModule.php
  classes/Refund.php
  classes/Repository/PaypalAccountRepository.php
  classes/Repository/PsAccountRepository.php
  classes/Translations/Translations.php
  classes/ValidateOrder.php
  controllers/admin/AdminAjaxPrestashopCheckoutController.php
  controllers/front/DispatchWebHook.php
  controllers/front/PaymentCard16.php
  controllers/front/PaymentPaypal16.php
  ps_checkout.php
  tests/PaymentCreateOrderTest.php
  tests/phpstan/phpstan.neon
  upgrade/upgrade-1.2.10.php
Labels: Feature

#300 Update wordings
  classes/Translations/Translations.php
  ps_checkout.php
  translations/fr.php
  views/templates/hook/payment.tpl
Labels: enhancement

#304 Fix intent
  classes/ExpressCheckout.php
  controllers/front/PaymentCard16.php
  controllers/front/PaymentPaypal16.php
  ps_checkout.php
Labels: bug

#305 Update translations
  translations/de.php
  translations/es.php
  translations/fr.php
  translations/it.php
  translations/nl.php
  translations/pl.php
  translations/pt.php
Labels: enhancement

#303 Improve express checkout design
  ps_checkout.php
  views/css/payments.css
  views/js/hideOtherPaymentOptions.js
  views/templates/front/paymentOptions/expressCheckout.tpl
Labels: enhancement

#306 Set address delivery on each product of the cart in order to get carriers in the checkout process
  controllers/front/ExpressCheckout.php
Labels: bug

#307 update vue js config not working with github action build
  _dev/vue.config.js
Labels: bug

#308 Fix missing return on installConfiguration()
  ps_checkout.php
Labels: bug
