Repository PrestaShopCorp/ps_checkout, pull requests merged in 2020-03, with the labels that each got.

#314 Fix logs path on PrestaShop 1.6
  classes/Factory/CheckoutLogger.php
Labels: bug

#312 Multistore ShopUuid manager and Multistore fixer
  _dev/src/pages/Debug.vue
  classes/Api/Payment/Client/PaymentClient.php
  classes/Api/Psx/Client/PsxClient.php
  classes/MultiStoreFixer.php
  classes/Presenter/Store/Modules/ContextModule.php
  classes/ShopUuidManager.php
  controllers/front/DispatchWebHook.php
  ps_checkout.php
  upgrade/upgrade-1.3.0.php
Labels: bug, need review

#317 Fix translations for reporting
  classes/Translations/Translations.php
Labels: bug

#310 Set locale on PayPal
  controllers/front/PaymentCard16.php
  controllers/front/PaymentPaypal16.php
  ps_checkout.php
  views/templates/front/paymentCardConfirmation.tpl
  views/templates/front/paymentOptions/paypal.tpl
  views/templates/front/paymentPaypalConfirmation.tpl
Labels: enhancement

#319 Fix reporting lot1 with multistore
  classes/Presenter/Order/OrderPendingPresenter.php
  classes/Presenter/Transaction/TransactionPresenter.php
  controllers/admin/AdminAjaxPrestashopCheckoutController.php
Labels: bug, need review

#321 Fix webhook change order state
  classes/webHookDispatcher/OrderDispatcher.php
Labels: bug

#313 Update/design improvments
  .gitignore
  _dev/src/App.vue
  _dev/src/components/block/card-status.vue
  _dev/src/components/block/paypal-status.vue
  _dev/src/components/block/rounding-banner.vue
  _dev/src/components/panel/account-list.vue
  _dev/src/components/panel/payment-acceptance.vue
  _dev/src/components/panel/psx-form.vue
  classes/Translations/Translations.php
Labels: enhancement

#320 Improve queries on module installation for slowest instance
  ps_checkout.php
Labels: enhancement

#323 Add translations for reporting columns
  _dev/src/components/block/reporting.vue
  classes/Presenter/Transaction/TransactionPresenter.php
  classes/Translations/Translations.php
Labels: enhancement

#318 Update translations
  translations/de.php
  translations/es.php
  translations/fr.php
  translations/it.php
  translations/nl.php
  translations/pl.php
  translations/pt.php
Labels: enhancement, need review

#327 Fix missing image on express checkout payment
  ps_checkout.php
  views/img/paypal_express.png
Labels: bug

#329 Quick fix transaction id
  classes/ValidateOrder.php
  controllers/front/ValidateOrder.php
Labels: bug

#324 Quickfix refund
  classes/Refund.php
  ps_checkout.php
Labels: bug

#326 Continuous delivery
  .github/workflows/checkout-cd-inte.yml
  .github/workflows/checkout-cd-prod-beta.yml
Labels: quality insurance needed

#334 Avoid JS error Uncaught (in promise)
  _dev/src/components/panel/account-list.vue
  _dev/src/components/panel/psx-form.vue
  _dev/src/pages/ResetPassword.vue
  _dev/src/pages/Signin.vue
  _dev/src/pages/Signup.vue
Labels: bug
