Repository PrestaShopCorp/ps_checkout, pull requests merged in 2020-01, with the labels that each got.

#236 Adds capability to disable hosted fields
  _dev/src/components/form/checkbox.vue
  _dev/src/components/panel/active-payment.vue
  _dev/src/store/modules/configuration/actions.js
  _dev/src/store/modules/configuration/mutation-types.js
  _dev/src/store/modules/configuration/mutations.js
  classes/Entity/PaypalAccount.php
  classes/Presenter/Store/Modules/ConfigurationModule.php
  classes/Repository/PaypalAccountRepository.php
  controllers/admin/AdminAjaxPrestashopCheckoutController.php
  ps_checkout.php
  upgrade/upgrade-1.2.9.php
Labels: enhancement, need review

#239 Add docker nodejs
  .travis.yml
  Makefile
  docker-compose.yml
Labels: enhancement

#262 Avoid to throw an exception when we cannot update the status of the p…
  _dev/src/App.vue
  _dev/src/components/block/account-status-paypal.vue
  _dev/src/components/panel/account-list.vue
  _dev/src/components/panel/active-payment.vue
  _dev/src/pages/Accounts.vue
  _dev/src/pages/ResetPassword.vue
  _dev/src/pages/Signin.vue
  _dev/src/pages/Signup.vue
  _dev/src/store/modules/paypal/actions.js
  _dev/src/store/modules/paypal/mutation-types.js
  _dev/src/store/modules/paypal/mutations.js
  _dev/vue.config.js
  classes/Entity/PaypalAccount.php
  classes/Presenter/Store/Modules/PaypalModule.php
  classes/Translations/Translations.php
  classes/Updater/PaypalAccountUpdater.php
  controllers/admin/AdminAjaxPrestashopCheckoutController.php
  controllers/admin/AdminPaypalOnboardingPrestashopCheckoutController.php
Labels: enhancement

#272 Fix WebHook on nginx
  controllers/front/DispatchWebHook.php
Labels: bug

#273 Fix path of javascript for express checkout
  classes/ExpressCheckout.php
Labels: bug

#277 handle icon copy when file does not exist
  classes/OrderStates.php
Labels: enhancement

#274 Fix hardcoded cms id for TermsAndConditions
  ps_checkout.php
  views/templates/front/paymentOptions/paypal.tpl
Labels: enhancement

#276 Add hook displayInvoiceLegalFreeText
  classes/Entity/OrderMatrice.php
  ps_checkout.php
  upgrade/upgrade-1.2.12.php
Labels: Feature
