Repository PrestaShopCorp/ps_checkout, pull requests merged in 2020-04, with the labels that each got.

#335 Improve payment restrictions when new shop created with multistore
  ps_checkout.php
Labels: enhancement

#338 Avoid Order with OrderState Payment error
  classes/ValidateOrder.php
Labels: bug

#341 Add hookDisplayAdminOrderLeft to display PayPal Order Id
  ps_checkout.php
  upgrade/upgrade-1.4.0.php
  views/templates/hook/displayAdminOrderLeft.tpl
Labels: Feature

#340 Avoid redirect in webhook
  controllers/front/DispatchWebHook.php
Labels: bug

#339 Remove check of PayPal merchant id, already done in checkPSLSignature
  controllers/front/DispatchWebHook.php
Labels: bug, waiting for author

#336 Add OrderPayment on webhook confirm order is paid
  classes/webHookDispatcher/OrderDispatcher.php
Labels: bug

#342 Fix webhook sent json encoded data
  classes/WebHookNock.php
  classes/webHookDispatcher/OrderDispatcher.php
  controllers/front/DispatchWebHook.php
Labels: bug

#343 Fix refund webhook validation
  classes/webHookValidation/WebHookValidation.php
Labels: bug

#345 Remove our admin controller from SEO & URLs page
  ps_checkout.php
  upgrade/upgrade-1.4.0.php
Labels: bug

#346 Fix javascript conflict with test()
  ps_checkout.php
  views/js/initPaypalAndCard.js
  views/templates/front/paymentOptions/hosted-fields.tpl
Labels: bug

#347 Improve PayPal Refund
  classes/Handler/CreatePaypalOrderHandler.php
  classes/PaypalOrder.php
  classes/webHookDispatcher/OrderDispatcher.php
  controllers/front/ExpressCheckout.php
  ps_checkout.php
  upgrade/upgrade-1.4.0.php
  views/templates/hook/displayAdminOrderLeft.tpl
Labels: PM Approved, enhancement

#348 Improve support of PayPal SDK errors
  classes/HostedFieldsErrors.php
  upgrade/upgrade-1.4.0.php
Labels: enhancement

#352 Updated user guide PDF files - Added NL, PL, PT
  classes/Presenter/Store/Modules/ContextModule.php
  docs/readme_en.pdf
  docs/readme_es.pdf
  docs/readme_fr.pdf
  docs/readme_it.pdf
  docs/readme_nl.pdf
  docs/readme_pl.pdf
  docs/readme_pt.pdf
Labels: enhancement

#337 Fix "Credit and Debit Cards" activation status
  _dev/src/components/block/card-status.vue
  _dev/src/components/panel/account-list.vue
  _dev/src/pages/Accounts.vue
  classes/Translations/Translations.php
Labels: bug

#353 Improve PayPal Sdk link building
  classes/Builder/PayPalSdkLink/PayPalSdkLinkBuilder.php
  classes/Builder/PayPalSdkLink/index.php
  classes/Entity/PaypalAccount.php
  classes/ExpressCheckout.php
  classes/PersistentConfiguration.php
  classes/Repository/PaypalAccountRepository.php
  controllers/front/PaymentCard16.php
  controllers/front/PaymentPaypal16.php
  ps_checkout.php
  views/templates/front/expressCheckout.tpl
  views/templates/front/paymentCardConfirmation.tpl
  views/templates/front/paymentOptions/paypal.tpl
  views/templates/front/paymentPaypalConfirmation.tpl
Labels: enhancement

#357 Fix wrong firstname and lastname values in payer node
  classes/Builder/Payload/OrderPayloadBuilder.php
Labels: bug

#358 Fix missing PayPal Account Status
  _dev/src/components/panel/account-list.vue
  classes/Repository/PaypalAccountRepository.php
  classes/Updater/PaypalAccountUpdater.php
Labels: bug

#356 Hide shop context panel with multishop in configuration page
  views/templates/admin/configuration.tpl
Labels: bug

#355 Fix PayPal Sdk locale - let PayPal determine the better locale
  classes/Builder/PayPalSdkLink/PayPalSdkLinkBuilder.php
Labels: bug

#354 Fix multiple orderstate
  upgrade/upgrade-1.4.0.php
Labels: bug

#359 Fix unsaved PayPal Order will cause fail of webhook
  classes/ObjectModel/OrderMatrice.php
Labels: bug

#360 Improve label on Order View with colors
  views/templates/hook/displayAdminOrderLeft.tpl
Labels: enhancement
