Repository PrestaShopCorp/ps_checkout, pull requests merged in 2020-05, with the labels that each got.

#363 Fix hosted-fields
  classes/Builder/PayPalSdkLink/PayPalSdkLinkBuilder.php
Labels: bug

#364 Add support of outofstock order state
  classes/ValidateOrder.php
  classes/webHookDispatcher/OrderDispatcher.php
Labels: enhancement

#365 Fix express checkout : display only PayPal button
  classes/Builder/PayPalSdkLink/PayPalSdkLinkBuilder.php
Labels: bug

#367 Fix payment method name translation on webhook
  classes/webHookDispatcher/OrderDispatcher.php
Labels: bug

#369 Fix performance issue on hook ActionFrontControllerSetMedia
  ps_checkout.php
Labels: bug

#368 Fix notice on others modules configuration page
  ps_checkout.php
Labels: bug

#366 Fix date timezone received from PayPal
  classes/Presenter/Date/DatePresenter.php
  classes/Presenter/Order/OrderPresenter.php
  classes/webHookDispatcher/OrderDispatcher.php
Labels: bug

#370 Fix missing translations
  classes/Translations/Translations.php
Labels: bug

#371 Fix double OrderPayment
  classes/webHookDispatcher/OrderDispatcher.php
Labels: bug

#372 Fix default value for isPaymentMethodEnabled on PrestaShop 1.6
  classes/Repository/PaypalAccountRepository.php
Labels: bug

#373 Improve Order View display
  views/templates/admin/ajaxPayPalOrder.tpl
  views/templates/admin/ajaxPayPalOrderLegacy.tpl
Labels: enhancement

#374 Improve logger
  classes/Api/GenericClient.php
  classes/Factory/CheckoutLogger.php
  classes/Faq/Faq.php
  classes/Handler/CreatePaypalOrderHandler.php
  classes/OrderStates.php
  classes/Refund.php
  classes/ValidateOrder.php
  classes/WebHookNock.php
  classes/WebHookOrder.php
  controllers/front/ValidateOrder.php
  upgrade/upgrade-1.2.9.php
Labels: enhancement

#375 Fix double OrderPayment
  classes/webHookDispatcher/OrderDispatcher.php
Labels: bug

#377 Fix permission issue on upgrade-1.4.0 due to Meta::delete()
  upgrade/upgrade-1.4.0.php
Labels: bug

#378 Handle Guzzle exception (Curl)
  _dev/src/components/block/onboarding.vue
  _dev/src/components/panel/account-list.vue
  _dev/src/components/panel/psx-form.vue
  _dev/src/pages/ResetPassword.vue
  _dev/src/pages/Signin.vue
  _dev/src/pages/Signup.vue
  _dev/src/store/modules/paypal/actions.js
  _dev/src/store/modules/psx/actions.js
  classes/Api/GenericClient.php
  controllers/admin/AdminAjaxPrestashopCheckoutController.php
Labels: bug

#379 Fix PSX form response
  _dev/src/components/panel/psx-form.vue
  controllers/admin/AdminAjaxPrestashopCheckoutController.php
Labels: bug

#380 Fix fatal error on API Client
  classes/Api/GenericClient.php
Labels: bug

#381 Rename function name to avoid conflicts
  upgrade/upgrade-1.2.9.php
Labels: bug

#311 Upgrade PHPStan and extend PrestaShop rules
  .github/workflows/php.yml
  classes/Api/Payment/Order.php
  classes/Builder/Payload/OnboardingPayloadBuilder.php
  classes/Builder/Payload/OrderPayloadBuilder.php
  classes/Entity/PaypalAccount.php
  classes/OrderStates.php
  classes/Presenter/Store/Modules/ContextModule.php
  classes/ShopUuidManager.php
  classes/webHookDispatcher/OrderDispatcher.php
  composer.json
  composer.lock
  controllers/front/DispatchWebHook.php
  controllers/front/ExpressCheckout.php
  ps_checkout.php
  tests/phpstan/bootstrap.php
  tests/phpstan/phpstan.neon
  upgrade/upgrade-1.2.9.php
Labels: enhancement

#383 Fix Rename function name to avoid conflicts
  upgrade/upgrade-1.2.9.php
Labels: bug

#384 Fix Header can't be empty on dispatch webhook
  controllers/front/DispatchWebHook.php
Labels: bug

#382 Fix Cart Presenter - Customer not found in some case
  classes/Builder/Payload/OrderPayloadBuilder.php
  classes/Handler/CreatePaypalOrderHandler.php
  classes/Presenter/Cart/CartPresenter.php
Labels: bug

#349 Introduce Service Container with Dependency Injection
  classes/Cache/CacheDirectory.php
  classes/DependencyInjection/ContainerProvider.php
  composer.json
  composer.lock
  config/admin/services.yml
  config/common.yml
  config/front/services.yml
  ps_checkout.php
  tests/Unit/Cache/CacheDirectoryTest.php
  tests/Unit/phpunit.xml
Labels: enhancement

#386 Update translations
  translations/de.php
  translations/es.php
  translations/fr.php
  translations/it.php
  translations/nl.php
  translations/pl.php
  translations/pt.php
Labels: enhancement

#387 Fix express checkout
  controllers/front/ExpressCheckout.php
  ps_checkout.php
  translations/de.php
  translations/es.php
  translations/fr.php
  translations/it.php
  translations/nl.php
  translations/pl.php
  translations/pt.php
  upgrade/upgrade-1.4.1.php
  views/js/hideOtherPaymentOptions.js
  views/templates/front/expressCheckout.tpl
  views/templates/hook/displayPaymentTop.tpl
Labels: bug

#388 Bump version 1.4.1
  config.xml
  ps_checkout.php
Labels: PM Approved

#392 Fix duplicate OrderState on weird case
  classes/ValidateOrder.php
Labels: bug

#390 Improve exception, webhook http code, error handling on validateOrder
  classes/Adapter/LinkAdapter.php
  classes/Api/GenericClient.php
  classes/Api/Payment/Order.php
  classes/Builder/Payload/OrderPayloadBuilder.php
  classes/Entity/PaypalAccount.php
  classes/Entity/PsAccount.php
  classes/Exception/PayPalException.php
  classes/Exception/PsCheckoutException.php
  classes/Exception/index.php
  classes/Handler/CreatePaypalOrderHandler.php
  classes/Handler/Response/ResponseApiHandler.php
  classes/MultiStoreFixer.php
  classes/OrderStates.php
  classes/PayPalError.php
  classes/PayPalProcessorResponse.php
  classes/PaypalOrder.php
  classes/Presenter/Date/DatePresenter.php
  classes/Presenter/Order/OrderPendingPresenter.php
  classes/Presenter/Store/Modules/PsxModule.php
  classes/Presenter/Store/StorePresenter.php
  classes/Presenter/Transaction/TransactionPresenter.php
  classes/PsxData/PsxDataValidation.php
  classes/Refund.php
  classes/ShopUuidManager.php
  classes/Updater/PaypalAccountUpdater.php
  classes/ValidateOrder.php
  classes/WebHookNock.php
  classes/WebHookOrder.php
  classes/exception/PsCheckoutException.php
  classes/exception/fatalException.php
  classes/exception/notAcceptableException.php
  classes/exception/unauthorizedException.php
  classes/exception/unprocessableException.php
  classes/webHookDispatcher/MerchantDispatcher.php
  classes/webHookDispatcher/OrderDispatcher.php
  classes/webHookValidation/WebHookValidation.php
  controllers/front/DispatchWebHook.php
  controllers/front/ValidateOrder.php
  ps_checkout.php
  tests/PaymentCreateOrderTest.php
  tests/WebHookValidationTest.php
  views/templates/front/validateOrder.tpl
  views/templates/front/validateOrderLegacy.tpl
  views/templates/hook/displayPaymentTop.tpl
Labels: PM Approved, bug

#396 Handle contingency errors
  classes/HostedFieldsErrors.php
  views/js/initCardPayment.js
  views/js/initPaypalAndCard.js
  views/templates/front/expressCheckout.tpl
  views/templates/front/paymentCardConfirmation.tpl
  views/templates/front/paymentOptions/hosted-fields.tpl
  views/templates/front/paymentOptions/paypal.tpl
  views/templates/front/paymentPaypalConfirmation.tpl
Labels: bug

#397 Fix missing checkboxes for currency restrictions
  ps_checkout.php
Labels: bug

#398 Fix display of PayPal buttons on PrestaShop 1.6
  views/templates/front/paymentPaypalConfirmation.tpl
Labels: bug

#399 Fix currency restrictions
  upgrade/upgrade-1.5.0.php
Labels: bug

#400 Fix Uncaught SyntaxError: Unexpected token p in JSON
  views/js/initCardPayment.js
  views/js/initPaypalAndCard.js
  views/js/initPaypalPayment.js
  views/templates/front/expressCheckout.tpl
  views/templates/front/paymentCardConfirmation.tpl
  views/templates/front/paymentOptions/paypal.tpl
  views/templates/front/paymentPaypalConfirmation.tpl
Labels: bug
