Repository PrestaShopCorp/ps_checkout, pull requests merged in 2021-02, with the labels that each got.

#684 Fixed bug related to onClick on Smart Buttons (no check)
  _dev/js/front/src/components/common/smart-button.component.js
Labels: bug, waiting for merge

#677 PayPal Value Banner
  _dev/js/back/src/App.vue
  _dev/js/back/src/assets/images/funding-sources/amex.svg
  _dev/js/back/src/assets/images/funding-sources/mastercard.svg
  _dev/js/back/src/assets/images/funding-sources/visa.svg
  _dev/js/back/src/assets/images/lamp.svg
  _dev/js/back/src/assets/images/shopping-cart.svg
  _dev/js/back/src/components/banner/paypal-value-proposition.vue
  _dev/js/back/src/store/modules/paypal/actions.js
  _dev/js/back/src/store/modules/paypal/mutation-types.js
  _dev/js/back/src/store/modules/paypal/mutations.js
  config/admin/services.yml
  config/common.yml
  controllers/admin/AdminAjaxPrestashopCheckoutController.php
  src/OnBoarding/Step/ValueBanner.php
  src/Presenter/Store/Modules/ContextModule.php
  src/Translations/Translations.php
  views/img/amex.svg
  views/img/lamp.svg
  views/img/mastercard.svg
  views/img/shopping-cart.svg
  views/img/visa.svg
Labels: Feature, waiting for PM

#680 PAYSHIP-858 Get customer country by his IP
  config/common.yml
  src/Context/PrestaShopContext.php
  src/Customer.php
  src/Merchant.php
Labels: Feature, WIP

#672 ISO codes compatibility with PayPal improvement
  _dev/js/back/src/components/banner/paypal-incompatible-country.vue
  _dev/js/back/src/components/banner/paypal-incompatible-currency.vue
  _dev/js/back/src/store/modules/context/getters.js
  _dev/js/front/package-lock.json
  ps_checkout.php
  src/PayPal/PayPalConfiguration.php
  src/Presenter/Store/Modules/ContextModule.php
  src/Repository/PayPalCodeRepository.php
  src/Translations/Translations.php
  upgrade/upgrade-2.6.0.php
  views/css/incompatible-banner.css
  views/templates/hook/adminAfterHeader/incompatibleCodes.tpl
Labels: enhancement, need review, waiting for PM

#695 Fix failed install on Addons
  _dev/js/back/src/pages/Accounts.vue
  config.xml
  ps_checkout.php
  src/PayPal/PayPalConfiguration.php
Labels: bug

#676 100% secure payments label added for payment by card
  src/FundingSource/FundingSourceTranslationProvider.php
  translations/de.php
  translations/en.php
  translations/es.php
  translations/fr.php
  translations/it.php
  translations/nl.php
  translations/pl.php
  translations/pt.php
Labels: PM Approved, enhancement

#696 Run PHPStan for src folder
  src/Dispatcher/OrderDispatcher.php
  src/Logger/LoggerFactory.php
  src/Logger/LoggerFilename.php
  src/OnBoarding/Step/LiveStep.php
  src/OnBoarding/Step/ValueBanner.php
  src/PayPal/PayPalConfiguration.php
  src/PersistentConfiguration.php
  src/Presenter/Store/Modules/ContextModule.php
  src/Presenter/Transaction/TransactionPresenter.php
  src/Refund.php
  src/Repository/CountryRepository.php
  src/Repository/OrderPaymentRepository.php
  src/Shop/ShopProvider.php
  src/Updater/PaypalAccountUpdater.php
  src/ValidateOrder.php
  tests/phpstan/phpstan-PS-1.6.neon
  tests/phpstan/phpstan-PS-1.7.neon
Labels: need review

#669 ExpressCheckout 1.6
  _dev/js/back/src/components/panel/express-checkout.vue
  _dev/js/back/src/pages/Customize.vue
  _dev/js/front/src/components/1_6/express-button-cart.component.js
  _dev/js/front/src/components/1_6/express-button-checkout.component.js
  _dev/js/front/src/components/1_6/express-button-product.component.js
  _dev/js/front/src/components/1_6/payment-options.component.js
  _dev/js/front/src/components/common/express-checkout-button.component.js
  _dev/js/front/src/components/ps-checkout-express.component/ps-checkout-express-ps1_6.component.js
  _dev/js/front/src/components/ps-checkout-express.component/ps-checkout-express-ps1_7.component.js
  _dev/js/front/src/components/ps-checkout.component/ps-checkout-ps1_6.component.js
  _dev/js/front/src/service/prestashop.service/index.js
  _dev/js/front/src/service/prestashop.service/prestashop-ps1_6.service.js
  _dev/js/front/src/service/prestashop.service/prestashop-ps1_7.service.js
  config.xml
  controllers/front/ExpressCheckout.php
  package-lock.json
  ps_checkout.php
  src/Updater/CustomerUpdater.php
  tests/phpstan/phpstan-PS-1.7.neon
  upgrade/upgrade-2.9.0.php
  views/css/payments16.css
  views/templates/hook/displayPayment.tpl
  views/templates/hook/displayPaymentTop.tpl
Labels: Feature
