Repository PrestaShopCorp/ps_checkout, pull requests merged in 2021-03, with the labels that each got.

#717 CI/CD - Use new module service accounts
  .github/workflows/checkout-cd-inte.yml
  .github/workflows/checkout-cd-prod-beta.yml
Labels: quality insurance needed

#707 [PAYSHIP-778] Added tooltip on CVV for 1.6 and 1.7
  translations/de.php
  translations/en.php
  translations/es.php
  translations/fr.php
  translations/it.php
  translations/nl.php
  translations/pl.php
  translations/pt.php
  views/css/payments.css
  views/css/payments16.css
  views/img/cvv.svg
  views/templates/hook/displayPayment.tpl
  views/templates/hook/paymentOptions.tpl
Labels: Feature, waiting for PM

#708 Payment Method Logos block
  config.xml
  ps_checkout.php
  src/ShopContext.php
  upgrade/upgrade-2.12.0.php
  views/css/payments.css
  views/img/lock_checkout.svg
  views/templates/hook/displayExpressCheckout.tpl
  views/templates/hook/displayProductAdditionalInfo.tpl
Labels: Feature
