Repository PrestaShopCorp/ps_checkout, pull requests merged in 2022-06, with the labels that each got.

#896 PAYSHIP-1824 - Fix missing PayPal Client Token
  _dev/js/front/src/api/ps-checkout.api.js
  _dev/js/front/src/core/app.js
  config/common.yml
  controllers/front/token.php
  ps_checkout.php
  src/Api/Payment/Order.php
  src/Exception/PsCheckoutException.php
  src/PayPal/PayPalClientTokenProvider.php
  src/Validator/FrontControllerValidator.php
Labels: bug

#893 PAYSHIP-1793 - Add X-Robots-Tag to front controllers
  controllers/front/DispatchWebHook.php
  src/Controller/AbstractFrontController.php
Labels: bug

#892 PAYSHIP-1800 - Fix missing payer phone on payload
  composer.json
  composer.lock
  src/Builder/Payload/OrderPayloadBuilder.php
Labels: bug

#884 PAYSHIP-1771 Do not retry for capture or refund
  src/Api/Payment/Client/PaymentClient.php
Labels: bug

#848 [PAYSHIP-1776] Fix loader popup too large
  views/css/payments.css
  views/css/payments16.css
Labels: bug

#855 [PAYSHIP-1585] Added payment method disabling and warning messages for merchants who can't receive payments
  _dev/js/back/src/App.vue
  ps_checkout.php
  src/Presenter/Store/Modules/ConfigurationModule.php
  src/Translations/Translations.php
  src/ValidateOrder.php
  translations/de.php
  translations/en.php
  translations/es.php
  translations/fr.php
  translations/it.php
  translations/nl.php
  translations/pl.php
  translations/pt.php
Labels: Feature

#849 [PAYSHIP-1778] Update npm packages
  _dev/js/back/package-lock.json
  _dev/js/back/package.json
  _dev/js/front/package-lock.json
Labels: dependencies

#883 PAYSHIP-1770 - Handle PAYMENT_DENIED
  controllers/front/validate.php
  src/Exception/PayPalException.php
  src/PayPalError.php
  translations/de.php
  translations/en.php
  translations/es.php
  translations/fr.php
  translations/it.php
  translations/nl.php
  translations/pl.php
  translations/pt.php
Labels: bug

#894 PAYSHIP-1806 - Catch Sentry exception to avoid fatal error
  ps_checkout.php
  src/Handler/ExceptionHandler.php
Labels: bug

#895 PAYSHIP-1820 - Force execution of global actions with CONTEXT_ALL on multishop
  ps_checkout.php
  upgrade/upgrade-1.2.10.php
  upgrade/upgrade-1.2.11.php
  upgrade/upgrade-1.2.12.php
  upgrade/upgrade-1.3.0.php
  upgrade/upgrade-1.4.0.php
  upgrade/upgrade-1.4.1.php
  upgrade/upgrade-1.5.0.php
  upgrade/upgrade-1.5.1.php
  upgrade/upgrade-1.5.2.php
  upgrade/upgrade-2.0.0.php
  upgrade/upgrade-2.1.0.php
  upgrade/upgrade-2.10.0.php
  upgrade/upgrade-2.11.0.php
  upgrade/upgrade-2.15.3.php
  upgrade/upgrade-2.15.4.php
  upgrade/upgrade-2.18.0.php
  upgrade/upgrade-2.19.0.php
  upgrade/upgrade-2.2.0.php
  upgrade/upgrade-2.3.0.php
  upgrade/upgrade-2.7.0.php
  upgrade/upgrade-2.9.0.php
Labels: bug
