Repository PrestaShopCorp/ps_checkout, pull requests merged in 2022-01, with the labels that each got.

#764 Custom ENV loader and guzzle compatibility fix
  composer.json
  composer.lock
  config/common.yml
  ps_checkout.php
  src/Api/GenericClient.php
  src/Environment/Env.php
  src/Environment/EnvLoader.php
Labels: bug

#835 Enhance OrderState checking at install
  src/OrderStates.php
Labels: bug

#832 Fixed error handling for errors returned by ajax
  views/js/adminOrderView.js
Labels: bug

#823 PAYSHIP-834 - Adds a retry when PSL timeout
  src/Api/Payment/Client/PaymentClient.php
  src/Exception/HttpTimeoutException.php
  src/Exception/PsCheckoutException.php
Labels: enhancement

#825 PAYSHIP-1428 - Fix product page 4x message should use product price
  ps_checkout.php
Labels: bug

#798 PHPDoc array shapes definitions
  ps_checkout.php
Labels: technical
