Repository PrestaShopCorp/ps_checkout, pull requests merged in 2024-11, with the labels that each got.

#1279 Triiger release draft at merge PR
  .github/workflows/ps8-build-release.yml
Labels: ready to review

#1280 GitHub/trigger draft release at merge
  .github/workflows/ps8-build-release.yml
Labels: ready to review

#1281 GitHub/trigger draft release at merge
  .github/workflows/ps8-build-release.yml
Labels: ready to review

#1275 [PAYSHIP-3046] Order capture retry
  config.xml
  config/cache.yml
  controllers/front/payment.php
  controllers/front/validate.php
  ps_checkout.php
  src/Checkout/CheckoutChecker.php
  src/Checkout/EventSubscriber/CheckoutEventSubscriber.php
  src/Exception/PsCheckoutException.php
  src/PayPal/Order/Cache/PayPalOrderCache.php
  src/PayPal/Order/Cache/index.php
  src/PayPal/Order/CommandHandler/CapturePayPalOrderCommandHandler.php
  src/PayPal/Order/EventSubscriber/PayPalOrderEventSubscriber.php
  src/PayPal/Order/PaypalOrderDataProvider.php
  src/PayPal/Order/QueryHandler/GetPayPalOrderForCheckoutCompletedQueryHandler.php
  tests/Unit/Http/MaaslandHttpClientTest.php
Labels: integration deployment, ready to review

#1284 Fix PS 8 deployment
  .github/workflows/ps8-build-release.yml
Labels: ready to review

#1285 Fix/deploy workflow ps8
  .github/workflows/ps8-build-release.yml
Labels: ready to review

#1286 Fix/deploy workflow ps8
  .github/workflows/ps8-build-release.yml
Labels: ready to review

#1282 [PAYSHIP-3106] Deployment workflow PS 1.7.x
  .github/actions/auth-gcp/action.yml
  .github/workflows/build-release.yml
  .github/workflows/deploy.yml
  .github/workflows/js.yml
  .github/workflows/php.yml
  .github/workflows/push-to-bucket.yml
  .github/workflows/push-to-repository.yml
  .github/workflows/update-release-draft.yml
  .gitignore
Labels: integration deployment, preproduction deployment, ready to review

#1290 Deploy workflow ps8 - fix draft release
  .github/workflows/push-to-repository.yml
Labels: ready to review
